<?php
/**
 * BusinessquotesApi
 * PHP version 5
 *
 * @category Class
 * @package  Boracomputer\ITScope
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ITscope - Interactive API V20
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * Contact: support@itscope.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Boracomputer\ITScope\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Boracomputer\ITScope\ApiException;
use Boracomputer\ITScope\Configuration;
use Boracomputer\ITScope\HeaderSelector;
use Boracomputer\ITScope\ObjectSerializer;

/**
 * BusinessquotesApi Class Doc Comment
 *
 * @category Class
 * @package  Boracomputer\ITScope
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BusinessquotesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getQuoteByQuoteId
     *
     * Fetch a quote by the Tscope quote ID
     *
     * @param  string $quote_id ITscope quote ID (required)
     * @param  string $view View (document) (required)
     * @param  string $type Output data format (required)
     *
     * @throws \Boracomputer\ITScope\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Boracomputer\ITScope\Model\Quote[]
     */
    public function getQuoteByQuoteId($quote_id, $view, $type)
    {
        list($response) = $this->getQuoteByQuoteIdWithHttpInfo($quote_id, $view, $type);
        return $response;
    }

    /**
     * Operation getQuoteByQuoteIdWithHttpInfo
     *
     * Fetch a quote by the Tscope quote ID
     *
     * @param  string $quote_id ITscope quote ID (required)
     * @param  string $view View (document) (required)
     * @param  string $type Output data format (required)
     *
     * @throws \Boracomputer\ITScope\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Boracomputer\ITScope\Model\Quote[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getQuoteByQuoteIdWithHttpInfo($quote_id, $view, $type)
    {
        $returnType = '\Boracomputer\ITScope\Model\Quote[]';
        $request = $this->getQuoteByQuoteIdRequest($quote_id, $view, $type);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Boracomputer\ITScope\Model\Quote[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getQuoteByQuoteIdAsync
     *
     * Fetch a quote by the Tscope quote ID
     *
     * @param  string $quote_id ITscope quote ID (required)
     * @param  string $view View (document) (required)
     * @param  string $type Output data format (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getQuoteByQuoteIdAsync($quote_id, $view, $type)
    {
        return $this->getQuoteByQuoteIdAsyncWithHttpInfo($quote_id, $view, $type)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getQuoteByQuoteIdAsyncWithHttpInfo
     *
     * Fetch a quote by the Tscope quote ID
     *
     * @param  string $quote_id ITscope quote ID (required)
     * @param  string $view View (document) (required)
     * @param  string $type Output data format (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getQuoteByQuoteIdAsyncWithHttpInfo($quote_id, $view, $type)
    {
        $returnType = '\Boracomputer\ITScope\Model\Quote[]';
        $request = $this->getQuoteByQuoteIdRequest($quote_id, $view, $type);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getQuoteByQuoteId'
     *
     * @param  string $quote_id ITscope quote ID (required)
     * @param  string $view View (document) (required)
     * @param  string $type Output data format (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getQuoteByQuoteIdRequest($quote_id, $view, $type)
    {
        // verify the required parameter 'quote_id' is set
        if ($quote_id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $quote_id when calling getQuoteByQuoteId'
            );
        }
        // verify the required parameter 'view' is set
        if ($view === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $view when calling getQuoteByQuoteId'
            );
        }
        // verify the required parameter 'type' is set
        if ($type === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $type when calling getQuoteByQuoteId'
            );
        }

        $resourcePath = '/business/quotes/{quoteId}/{view}.{type}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($quote_id !== null) {
            $resourcePath = str_replace(
                '{' . 'quoteId' . '}',
                ObjectSerializer::toPathValue($quote_id),
                $resourcePath
            );
        }
        // path params
        if ($view !== null) {
            $resourcePath = str_replace(
                '{' . 'view' . '}',
                ObjectSerializer::toPathValue($view),
                $resourcePath
            );
        }
        // path params
        if ($type !== null) {
            $resourcePath = str_replace(
                '{' . 'type' . '}',
                ObjectSerializer::toPathValue($type),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/xml', 'application/json', 'text/xml']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/xml', 'application/json', 'text/xml'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getQuoteList
     *
     * Fetch a list of quotes
     *
     * @param  string $view View (document) (required)
     * @param  string $type Output data format (required)
     * @param  string $sort Sort the results (optional, default to LAST_MODIFIED)
     * @param  int $page Large result sets are bundled in multiple pages with 50 results per page. (optional, default to 1)
     *
     * @throws \Boracomputer\ITScope\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Boracomputer\ITScope\Model\Quote[]
     */
    public function getQuoteList($view, $type, $sort = 'LAST_MODIFIED', $page = '1')
    {
        list($response) = $this->getQuoteListWithHttpInfo($view, $type, $sort, $page);
        return $response;
    }

    /**
     * Operation getQuoteListWithHttpInfo
     *
     * Fetch a list of quotes
     *
     * @param  string $view View (document) (required)
     * @param  string $type Output data format (required)
     * @param  string $sort Sort the results (optional, default to LAST_MODIFIED)
     * @param  int $page Large result sets are bundled in multiple pages with 50 results per page. (optional, default to 1)
     *
     * @throws \Boracomputer\ITScope\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Boracomputer\ITScope\Model\Quote[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getQuoteListWithHttpInfo($view, $type, $sort = 'LAST_MODIFIED', $page = '1')
    {
        $returnType = '\Boracomputer\ITScope\Model\Quote[]';
        $request = $this->getQuoteListRequest($view, $type, $sort, $page);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Boracomputer\ITScope\Model\Quote[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getQuoteListAsync
     *
     * Fetch a list of quotes
     *
     * @param  string $view View (document) (required)
     * @param  string $type Output data format (required)
     * @param  string $sort Sort the results (optional, default to LAST_MODIFIED)
     * @param  int $page Large result sets are bundled in multiple pages with 50 results per page. (optional, default to 1)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getQuoteListAsync($view, $type, $sort = 'LAST_MODIFIED', $page = '1')
    {
        return $this->getQuoteListAsyncWithHttpInfo($view, $type, $sort, $page)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getQuoteListAsyncWithHttpInfo
     *
     * Fetch a list of quotes
     *
     * @param  string $view View (document) (required)
     * @param  string $type Output data format (required)
     * @param  string $sort Sort the results (optional, default to LAST_MODIFIED)
     * @param  int $page Large result sets are bundled in multiple pages with 50 results per page. (optional, default to 1)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getQuoteListAsyncWithHttpInfo($view, $type, $sort = 'LAST_MODIFIED', $page = '1')
    {
        $returnType = '\Boracomputer\ITScope\Model\Quote[]';
        $request = $this->getQuoteListRequest($view, $type, $sort, $page);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getQuoteList'
     *
     * @param  string $view View (document) (required)
     * @param  string $type Output data format (required)
     * @param  string $sort Sort the results (optional, default to LAST_MODIFIED)
     * @param  int $page Large result sets are bundled in multiple pages with 50 results per page. (optional, default to 1)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getQuoteListRequest($view, $type, $sort = 'LAST_MODIFIED', $page = '1')
    {
        // verify the required parameter 'view' is set
        if ($view === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $view when calling getQuoteList'
            );
        }
        // verify the required parameter 'type' is set
        if ($type === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $type when calling getQuoteList'
            );
        }

        $resourcePath = '/business/quotes/{view}.{type}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($sort !== null) {
            $queryParams['sort'] = ObjectSerializer::toQueryValue($sort);
        }
        // query params
        if ($page !== null) {
            $queryParams['page'] = ObjectSerializer::toQueryValue($page);
        }

        // path params
        if ($view !== null) {
            $resourcePath = str_replace(
                '{' . 'view' . '}',
                ObjectSerializer::toPathValue($view),
                $resourcePath
            );
        }
        // path params
        if ($type !== null) {
            $resourcePath = str_replace(
                '{' . 'type' . '}',
                ObjectSerializer::toPathValue($type),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/xml', 'application/json', 'text/csv', 'text/html', 'application/zip']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/xml', 'application/json', 'text/csv', 'text/html', 'application/zip'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation searchQuotes
     *
     * Fetch quotes by filters
     *
     * @param  string $view View (document) (required)
     * @param  string $type Output data format (required)
     * @param  string $filter Possible criteria are keywords, quoteno, status[DRAFT, PROGRESS, WON, LOST] e.g. quoteno&#x3D;MAN-20150126-10147 oder status&#x3D;WON. (required)
     * @param  string $sort Sort the results (optional, default to LAST_MODIFIED)
     * @param  int $page Large result sets are bundled in multiple pages with 50 results per page. (optional, default to 1)
     *
     * @throws \Boracomputer\ITScope\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Boracomputer\ITScope\Model\Quote[]
     */
    public function searchQuotes($view, $type, $filter, $sort = 'LAST_MODIFIED', $page = '1')
    {
        list($response) = $this->searchQuotesWithHttpInfo($view, $type, $filter, $sort, $page);
        return $response;
    }

    /**
     * Operation searchQuotesWithHttpInfo
     *
     * Fetch quotes by filters
     *
     * @param  string $view View (document) (required)
     * @param  string $type Output data format (required)
     * @param  string $filter Possible criteria are keywords, quoteno, status[DRAFT, PROGRESS, WON, LOST] e.g. quoteno&#x3D;MAN-20150126-10147 oder status&#x3D;WON. (required)
     * @param  string $sort Sort the results (optional, default to LAST_MODIFIED)
     * @param  int $page Large result sets are bundled in multiple pages with 50 results per page. (optional, default to 1)
     *
     * @throws \Boracomputer\ITScope\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Boracomputer\ITScope\Model\Quote[], HTTP status code, HTTP response headers (array of strings)
     */
    public function searchQuotesWithHttpInfo($view, $type, $filter, $sort = 'LAST_MODIFIED', $page = '1')
    {
        $returnType = '\Boracomputer\ITScope\Model\Quote[]';
        $request = $this->searchQuotesRequest($view, $type, $filter, $sort, $page);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Boracomputer\ITScope\Model\Quote[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation searchQuotesAsync
     *
     * Fetch quotes by filters
     *
     * @param  string $view View (document) (required)
     * @param  string $type Output data format (required)
     * @param  string $filter Possible criteria are keywords, quoteno, status[DRAFT, PROGRESS, WON, LOST] e.g. quoteno&#x3D;MAN-20150126-10147 oder status&#x3D;WON. (required)
     * @param  string $sort Sort the results (optional, default to LAST_MODIFIED)
     * @param  int $page Large result sets are bundled in multiple pages with 50 results per page. (optional, default to 1)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchQuotesAsync($view, $type, $filter, $sort = 'LAST_MODIFIED', $page = '1')
    {
        return $this->searchQuotesAsyncWithHttpInfo($view, $type, $filter, $sort, $page)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchQuotesAsyncWithHttpInfo
     *
     * Fetch quotes by filters
     *
     * @param  string $view View (document) (required)
     * @param  string $type Output data format (required)
     * @param  string $filter Possible criteria are keywords, quoteno, status[DRAFT, PROGRESS, WON, LOST] e.g. quoteno&#x3D;MAN-20150126-10147 oder status&#x3D;WON. (required)
     * @param  string $sort Sort the results (optional, default to LAST_MODIFIED)
     * @param  int $page Large result sets are bundled in multiple pages with 50 results per page. (optional, default to 1)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchQuotesAsyncWithHttpInfo($view, $type, $filter, $sort = 'LAST_MODIFIED', $page = '1')
    {
        $returnType = '\Boracomputer\ITScope\Model\Quote[]';
        $request = $this->searchQuotesRequest($view, $type, $filter, $sort, $page);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchQuotes'
     *
     * @param  string $view View (document) (required)
     * @param  string $type Output data format (required)
     * @param  string $filter Possible criteria are keywords, quoteno, status[DRAFT, PROGRESS, WON, LOST] e.g. quoteno&#x3D;MAN-20150126-10147 oder status&#x3D;WON. (required)
     * @param  string $sort Sort the results (optional, default to LAST_MODIFIED)
     * @param  int $page Large result sets are bundled in multiple pages with 50 results per page. (optional, default to 1)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function searchQuotesRequest($view, $type, $filter, $sort = 'LAST_MODIFIED', $page = '1')
    {
        // verify the required parameter 'view' is set
        if ($view === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $view when calling searchQuotes'
            );
        }
        // verify the required parameter 'type' is set
        if ($type === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $type when calling searchQuotes'
            );
        }
        // verify the required parameter 'filter' is set
        if ($filter === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $filter when calling searchQuotes'
            );
        }

        $resourcePath = '/business/quotes/search/{filter}/{view}.{type}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($sort !== null) {
            $queryParams['sort'] = ObjectSerializer::toQueryValue($sort);
        }
        // query params
        if ($page !== null) {
            $queryParams['page'] = ObjectSerializer::toQueryValue($page);
        }

        // path params
        if ($view !== null) {
            $resourcePath = str_replace(
                '{' . 'view' . '}',
                ObjectSerializer::toPathValue($view),
                $resourcePath
            );
        }
        // path params
        if ($type !== null) {
            $resourcePath = str_replace(
                '{' . 'type' . '}',
                ObjectSerializer::toPathValue($type),
                $resourcePath
            );
        }
        // path params
        if ($filter !== null) {
            $resourcePath = str_replace(
                '{' . 'filter' . '}',
                ObjectSerializer::toPathValue($filter),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/xml', 'application/json', 'text/csv', 'text/html', 'application/zip']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/xml', 'application/json', 'text/csv', 'text/html', 'application/zip'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
