<?php
/**
 * InvoiceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Boracomputer\ITScope
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ITscope - Interactive API V20
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * Contact: support@itscope.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Boracomputer\ITScope;

/**
 * InvoiceTest Class Doc Comment
 *
 * @category    Class */
// * @description Details zur Liste der &lt;a href&#x3D;\&quot;https://support.itscope.com/hc/de/articles/206814239\&quot;&gt;OpenTrans 2.1 INVOICE&lt;/a&gt; Dokumente
/**
 * @package     Boracomputer\ITScope
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InvoiceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Invoice"
     */
    public function testInvoice()
    {
    }

    /**
     * Test attribute "transaction_id"
     */
    public function testPropertyTransactionId()
    {
    }

    /**
     * Test attribute "last_update"
     */
    public function testPropertyLastUpdate()
    {
    }

    /**
     * Test attribute "document_url"
     */
    public function testPropertyDocumentUrl()
    {
    }
}
