<?php
/**
 * ProductTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Boracomputer\ITScope
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ITscope - Interactive API V20
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * Contact: support@itscope.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Boracomputer\ITScope;

/**
 * ProductTest Class Doc Comment
 *
 * @category    Class */
// * @description Produkt des ITscope-Katalogs.
/**
 * @package     Boracomputer\ITScope
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Product"
     */
    public function testProduct()
    {
    }

    /**
     * Test attribute "puid"
     */
    public function testPropertyPuid()
    {
    }

    /**
     * Test attribute "ean"
     */
    public function testPropertyEan()
    {
    }

    /**
     * Test attribute "manufacturer_sku"
     */
    public function testPropertyManufacturerSku()
    {
    }

    /**
     * Test attribute "icecat_id"
     */
    public function testPropertyIcecatId()
    {
    }

    /**
     * Test attribute "cnet_id"
     */
    public function testPropertyCnetId()
    {
    }

    /**
     * Test attribute "bechlem_id"
     */
    public function testPropertyBechlemId()
    {
    }

    /**
     * Test attribute "e_class"
     */
    public function testPropertyEClass()
    {
    }

    /**
     * Test attribute "manufacturer_id"
     */
    public function testPropertyManufacturerId()
    {
    }

    /**
     * Test attribute "manufacturer_name"
     */
    public function testPropertyManufacturerName()
    {
    }

    /**
     * Test attribute "product_name_with_manufacturer"
     */
    public function testPropertyProductNameWithManufacturer()
    {
    }

    /**
     * Test attribute "short_description"
     */
    public function testPropertyShortDescription()
    {
    }

    /**
     * Test attribute "long_description"
     */
    public function testPropertyLongDescription()
    {
    }

    /**
     * Test attribute "product_type_id"
     */
    public function testPropertyProductTypeId()
    {
    }

    /**
     * Test attribute "product_type_group_id"
     */
    public function testPropertyProductTypeGroupId()
    {
    }

    /**
     * Test attribute "product_type_group_name"
     */
    public function testPropertyProductTypeGroupName()
    {
    }

    /**
     * Test attribute "product_type_name"
     */
    public function testPropertyProductTypeName()
    {
    }

    /**
     * Test attribute "attribute_type_id1"
     */
    public function testPropertyAttributeTypeId1()
    {
    }

    /**
     * Test attribute "attribute_type_name1"
     */
    public function testPropertyAttributeTypeName1()
    {
    }

    /**
     * Test attribute "attribute_type_id2"
     */
    public function testPropertyAttributeTypeId2()
    {
    }

    /**
     * Test attribute "attribute_type_name2"
     */
    public function testPropertyAttributeTypeName2()
    {
    }

    /**
     * Test attribute "attribute_type_id3"
     */
    public function testPropertyAttributeTypeId3()
    {
    }

    /**
     * Test attribute "attribute_type_name3"
     */
    public function testPropertyAttributeTypeName3()
    {
    }

    /**
     * Test attribute "attribute_type_id4"
     */
    public function testPropertyAttributeTypeId4()
    {
    }

    /**
     * Test attribute "attribute_type_name4"
     */
    public function testPropertyAttributeTypeName4()
    {
    }

    /**
     * Test attribute "attribute_type_id5"
     */
    public function testPropertyAttributeTypeId5()
    {
    }

    /**
     * Test attribute "attribute_type_name5"
     */
    public function testPropertyAttributeTypeName5()
    {
    }

    /**
     * Test attribute "attribute_value1"
     */
    public function testPropertyAttributeValue1()
    {
    }

    /**
     * Test attribute "attribute_value2"
     */
    public function testPropertyAttributeValue2()
    {
    }

    /**
     * Test attribute "attribute_value3"
     */
    public function testPropertyAttributeValue3()
    {
    }

    /**
     * Test attribute "attribute_value4"
     */
    public function testPropertyAttributeValue4()
    {
    }

    /**
     * Test attribute "attribute_value5"
     */
    public function testPropertyAttributeValue5()
    {
    }

    /**
     * Test attribute "product_sub_type_id"
     */
    public function testPropertyProductSubTypeId()
    {
    }

    /**
     * Test attribute "product_sub_type"
     */
    public function testPropertyProductSubType()
    {
    }

    /**
     * Test attribute "product_line_id"
     */
    public function testPropertyProductLineId()
    {
    }

    /**
     * Test attribute "product_line"
     */
    public function testPropertyProductLine()
    {
    }

    /**
     * Test attribute "product_model"
     */
    public function testPropertyProductModel()
    {
    }

    /**
     * Test attribute "estimate_gross_weight"
     */
    public function testPropertyEstimateGrossWeight()
    {
    }

    /**
     * Test attribute "gross_dim_x"
     */
    public function testPropertyGrossDimX()
    {
    }

    /**
     * Test attribute "gross_dim_y"
     */
    public function testPropertyGrossDimY()
    {
    }

    /**
     * Test attribute "gross_dim_z"
     */
    public function testPropertyGrossDimZ()
    {
    }

    /**
     * Test attribute "customs_tariff_number"
     */
    public function testPropertyCustomsTariffNumber()
    {
    }

    /**
     * Test attribute "deeplink"
     */
    public function testPropertyDeeplink()
    {
    }

    /**
     * Test attribute "standard_html_datasheet"
     */
    public function testPropertyStandardHtmlDatasheet()
    {
    }

    /**
     * Test attribute "standard_pdf_datasheet"
     */
    public function testPropertyStandardPdfDatasheet()
    {
    }

    /**
     * Test attribute "manufacturer_site"
     */
    public function testPropertyManufacturerSite()
    {
    }

    /**
     * Test attribute "manufacturer_datasheet"
     */
    public function testPropertyManufacturerDatasheet()
    {
    }

    /**
     * Test attribute "image_thumb"
     */
    public function testPropertyImageThumb()
    {
    }

    /**
     * Test attribute "image_thumb_width"
     */
    public function testPropertyImageThumbWidth()
    {
    }

    /**
     * Test attribute "image_thumb_height"
     */
    public function testPropertyImageThumbHeight()
    {
    }

    /**
     * Test attribute "image1"
     */
    public function testPropertyImage1()
    {
    }

    /**
     * Test attribute "image_width1"
     */
    public function testPropertyImageWidth1()
    {
    }

    /**
     * Test attribute "image_height1"
     */
    public function testPropertyImageHeight1()
    {
    }

    /**
     * Test attribute "image2"
     */
    public function testPropertyImage2()
    {
    }

    /**
     * Test attribute "image_width2"
     */
    public function testPropertyImageWidth2()
    {
    }

    /**
     * Test attribute "image_height2"
     */
    public function testPropertyImageHeight2()
    {
    }

    /**
     * Test attribute "image3"
     */
    public function testPropertyImage3()
    {
    }

    /**
     * Test attribute "image_width3"
     */
    public function testPropertyImageWidth3()
    {
    }

    /**
     * Test attribute "image_height3"
     */
    public function testPropertyImageHeight3()
    {
    }

    /**
     * Test attribute "image4"
     */
    public function testPropertyImage4()
    {
    }

    /**
     * Test attribute "image_width4"
     */
    public function testPropertyImageWidth4()
    {
    }

    /**
     * Test attribute "image_height4"
     */
    public function testPropertyImageHeight4()
    {
    }

    /**
     * Test attribute "image5"
     */
    public function testPropertyImage5()
    {
    }

    /**
     * Test attribute "image_width5"
     */
    public function testPropertyImageWidth5()
    {
    }

    /**
     * Test attribute "image_height5"
     */
    public function testPropertyImageHeight5()
    {
    }

    /**
     * Test attribute "energy_label"
     */
    public function testPropertyEnergyLabel()
    {
    }

    /**
     * Test attribute "entry_date"
     */
    public function testPropertyEntryDate()
    {
    }

    /**
     * Test attribute "rank"
     */
    public function testPropertyRank()
    {
    }

    /**
     * Test attribute "qualification"
     */
    public function testPropertyQualification()
    {
    }

    /**
     * Test attribute "warranty_text"
     */
    public function testPropertyWarrantyText()
    {
    }

    /**
     * Test attribute "marketing_text"
     */
    public function testPropertyMarketingText()
    {
    }

    /**
     * Test attribute "html_specs"
     */
    public function testPropertyHtmlSpecs()
    {
    }

    /**
     * Test attribute "recommended_retail_price_net"
     */
    public function testPropertyRecommendedRetailPriceNet()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "price_calc"
     */
    public function testPropertyPriceCalc()
    {
    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {
    }

    /**
     * Test attribute "price_calc_vat"
     */
    public function testPropertyPriceCalcVat()
    {
    }

    /**
     * Test attribute "price_last_update"
     */
    public function testPropertyPriceLastUpdate()
    {
    }

    /**
     * Test attribute "price_supplier_id"
     */
    public function testPropertyPriceSupplierId()
    {
    }

    /**
     * Test attribute "price_supplier_name"
     */
    public function testPropertyPriceSupplierName()
    {
    }

    /**
     * Test attribute "price_supplier_item_id"
     */
    public function testPropertyPriceSupplierItemId()
    {
    }

    /**
     * Test attribute "price_supplier_sku"
     */
    public function testPropertyPriceSupplierSku()
    {
    }

    /**
     * Test attribute "stock_supplier_text"
     */
    public function testPropertyStockSupplierText()
    {
    }

    /**
     * Test attribute "stock_status"
     */
    public function testPropertyStockStatus()
    {
    }

    /**
     * Test attribute "stock_status_text"
     */
    public function testPropertyStockStatusText()
    {
    }

    /**
     * Test attribute "stock"
     */
    public function testPropertyStock()
    {
    }

    /**
     * Test attribute "external_stock"
     */
    public function testPropertyExternalStock()
    {
    }

    /**
     * Test attribute "incoming_stock"
     */
    public function testPropertyIncomingStock()
    {
    }

    /**
     * Test attribute "stock_availability_date"
     */
    public function testPropertyStockAvailabilityDate()
    {
    }

    /**
     * Test attribute "stock_last_update"
     */
    public function testPropertyStockLastUpdate()
    {
    }

    /**
     * Test attribute "aggregated_status"
     */
    public function testPropertyAggregatedStatus()
    {
    }

    /**
     * Test attribute "aggregated_status_text"
     */
    public function testPropertyAggregatedStatusText()
    {
    }

    /**
     * Test attribute "aggregated_stock"
     */
    public function testPropertyAggregatedStock()
    {
    }

    /**
     * Test attribute "aggregated_supplier_items"
     */
    public function testPropertyAggregatedSupplierItems()
    {
    }

    /**
     * Test attribute "supplier_item"
     */
    public function testPropertySupplierItem()
    {
    }

    /**
     * Test attribute "attribute"
     */
    public function testPropertyAttribute()
    {
    }

    /**
     * Test attribute "attribute_cluster"
     */
    public function testPropertyAttributeCluster()
    {
    }

    /**
     * Test attribute "accessory"
     */
    public function testPropertyAccessory()
    {
    }
}
