<?php
/**
 * ProductTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ITscope - Interactive API V20
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * Contact: support@itscope.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProductTypeTest Class Doc Comment
 *
 * @category    Class */
// * @description Typ eines Produkts, z.B. Server, Prozessor.
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductType"
     */
    public function testProductType()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "product_type_group"
     */
    public function testPropertyProductTypeGroup()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "attribute_type_id1"
     */
    public function testPropertyAttributeTypeId1()
    {
    }

    /**
     * Test attribute "attribute_type_name1"
     */
    public function testPropertyAttributeTypeName1()
    {
    }

    /**
     * Test attribute "attribute_type_id2"
     */
    public function testPropertyAttributeTypeId2()
    {
    }

    /**
     * Test attribute "attribute_type_name2"
     */
    public function testPropertyAttributeTypeName2()
    {
    }

    /**
     * Test attribute "attribute_type_id3"
     */
    public function testPropertyAttributeTypeId3()
    {
    }

    /**
     * Test attribute "attribute_type_name3"
     */
    public function testPropertyAttributeTypeName3()
    {
    }

    /**
     * Test attribute "attribute_type_id4"
     */
    public function testPropertyAttributeTypeId4()
    {
    }

    /**
     * Test attribute "attribute_type_name4"
     */
    public function testPropertyAttributeTypeName4()
    {
    }

    /**
     * Test attribute "attribute_type_id5"
     */
    public function testPropertyAttributeTypeId5()
    {
    }

    /**
     * Test attribute "attribute_type_name5"
     */
    public function testPropertyAttributeTypeName5()
    {
    }

    /**
     * Test attribute "attribute_type"
     */
    public function testPropertyAttributeType()
    {
    }
}
