<?php
/**
 * QuoteTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ITscope - Interactive API V20
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * Contact: support@itscope.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * QuoteTest Class Doc Comment
 *
 * @category    Class */
// * @description Detailinformationen zu einem Angebot
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QuoteTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Quote"
     */
    public function testQuote()
    {
    }

    /**
     * Test attribute "quote_id"
     */
    public function testPropertyQuoteId()
    {
    }

    /**
     * Test attribute "quote_no"
     */
    public function testPropertyQuoteNo()
    {
    }

    /**
     * Test attribute "short_url"
     */
    public function testPropertyShortUrl()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "last_modified"
     */
    public function testPropertyLastModified()
    {
    }

    /**
     * Test attribute "valid_until"
     */
    public function testPropertyValidUntil()
    {
    }

    /**
     * Test attribute "organisation"
     */
    public function testPropertyOrganisation()
    {
    }

    /**
     * Test attribute "person"
     */
    public function testPropertyPerson()
    {
    }

    /**
     * Test attribute "item_count"
     */
    public function testPropertyItemCount()
    {
    }

    /**
     * Test attribute "document_url"
     */
    public function testPropertyDocumentUrl()
    {
    }
}
