<?php
/**
 * SupplierItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ITscope - Interactive API V20
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * Contact: support@itscope.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SupplierItemTest Class Doc Comment
 *
 * @category    Class */
// * @description Bezugsquelle eines ITscope-Produkts. Ein konkretes Angebot eines auf ITscope gelisteten Distributors.
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SupplierItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SupplierItem"
     */
    public function testSupplierItem()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "ean"
     */
    public function testPropertyEan()
    {
    }

    /**
     * Test attribute "manufacturer_sku"
     */
    public function testPropertyManufacturerSku()
    {
    }

    /**
     * Test attribute "supplier_sku"
     */
    public function testPropertySupplierSku()
    {
    }

    /**
     * Test attribute "supplier_id"
     */
    public function testPropertySupplierId()
    {
    }

    /**
     * Test attribute "supplier_name"
     */
    public function testPropertySupplierName()
    {
    }

    /**
     * Test attribute "manufacturer_name"
     */
    public function testPropertyManufacturerName()
    {
    }

    /**
     * Test attribute "product_name"
     */
    public function testPropertyProductName()
    {
    }

    /**
     * Test attribute "long_description"
     */
    public function testPropertyLongDescription()
    {
    }

    /**
     * Test attribute "condition_id"
     */
    public function testPropertyConditionId()
    {
    }

    /**
     * Test attribute "condition_name"
     */
    public function testPropertyConditionName()
    {
    }

    /**
     * Test attribute "eol_product"
     */
    public function testPropertyEolProduct()
    {
    }

    /**
     * Test attribute "match_quality"
     */
    public function testPropertyMatchQuality()
    {
    }

    /**
     * Test attribute "ean_valid"
     */
    public function testPropertyEanValid()
    {
    }

    /**
     * Test attribute "special_offer"
     */
    public function testPropertySpecialOffer()
    {
    }

    /**
     * Test attribute "promotion"
     */
    public function testPropertyPromotion()
    {
    }

    /**
     * Test attribute "vat"
     */
    public function testPropertyVat()
    {
    }

    /**
     * Test attribute "copyright_levy"
     */
    public function testPropertyCopyrightLevy()
    {
    }

    /**
     * Test attribute "customs_tariff_number"
     */
    public function testPropertyCustomsTariffNumber()
    {
    }

    /**
     * Test attribute "country_of_origin"
     */
    public function testPropertyCountryOfOrigin()
    {
    }

    /**
     * Test attribute "gross_dim_x"
     */
    public function testPropertyGrossDimX()
    {
    }

    /**
     * Test attribute "gross_dim_y"
     */
    public function testPropertyGrossDimY()
    {
    }

    /**
     * Test attribute "gross_dim_z"
     */
    public function testPropertyGrossDimZ()
    {
    }

    /**
     * Test attribute "warranty_text"
     */
    public function testPropertyWarrantyText()
    {
    }

    /**
     * Test attribute "deeplink"
     */
    public function testPropertyDeeplink()
    {
    }

    /**
     * Test attribute "recommended_retail_price_net"
     */
    public function testPropertyRecommendedRetailPriceNet()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "price_calc"
     */
    public function testPropertyPriceCalc()
    {
    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {
    }

    /**
     * Test attribute "price_calc_vat"
     */
    public function testPropertyPriceCalcVat()
    {
    }

    /**
     * Test attribute "price_last_update"
     */
    public function testPropertyPriceLastUpdate()
    {
    }

    /**
     * Test attribute "stock_supplier_text"
     */
    public function testPropertyStockSupplierText()
    {
    }

    /**
     * Test attribute "stock_status"
     */
    public function testPropertyStockStatus()
    {
    }

    /**
     * Test attribute "stock_status_text"
     */
    public function testPropertyStockStatusText()
    {
    }

    /**
     * Test attribute "stock"
     */
    public function testPropertyStock()
    {
    }

    /**
     * Test attribute "external_stock"
     */
    public function testPropertyExternalStock()
    {
    }

    /**
     * Test attribute "incoming_stock"
     */
    public function testPropertyIncomingStock()
    {
    }

    /**
     * Test attribute "stock_availability_date"
     */
    public function testPropertyStockAvailabilityDate()
    {
    }

    /**
     * Test attribute "last_stock_update"
     */
    public function testPropertyLastStockUpdate()
    {
    }
}
