<?php
/**
 * BusinesscartsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Boracomputer\ITScope
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ITscope - Interactive API V20
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * Contact: support@itscope.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Boracomputer\ITScope;

use \Boracomputer\ITScope\Configuration;
use \Boracomputer\ITScope\ApiException;
use \Boracomputer\ITScope\ObjectSerializer;

/**
 * BusinesscartsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Boracomputer\ITScope
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BusinesscartsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addLineItem
     *
     * Add products to the cart.
     *
     */
    public function testAddLineItem()
    {
    }

    /**
     * Test case for createCart
     *
     * Create a cart.
     *
     */
    public function testCreateCart()
    {
    }

    /**
     * Test case for editCart
     *
     * Edit a cart.
     *
     */
    public function testEditCart()
    {
    }

    /**
     * Test case for getCartInfo
     *
     * Show cart.
     *
     */
    public function testGetCartInfo()
    {
    }

    /**
     * Test case for listCarts
     *
     * List all carts.
     *
     */
    public function testListCarts()
    {
    }

    /**
     * Test case for removeCart
     *
     * Remove a cart.
     *
     */
    public function testRemoveCart()
    {
    }

    /**
     * Test case for removeLineItem
     *
     * Remove products from the cart.
     *
     */
    public function testRemoveLineItem()
    {
    }
}
