<?php
/**
 * ProductsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Boracomputer\ITScope
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ITscope - Interactive API V20
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * Contact: support@itscope.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Boracomputer\ITScope;

use \Boracomputer\ITScope\Configuration;
use \Boracomputer\ITScope\ApiException;
use \Boracomputer\ITScope\ObjectSerializer;

/**
 * ProductsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Boracomputer\ITScope
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for export
     *
     * Download an export.
     *
     */
    public function testExport()
    {
    }

    /**
     * Test case for queryDatasheetById
     *
     * Fetch datasheet by ID.
     *
     */
    public function testQueryDatasheetById()
    {
    }

    /**
     * Test case for queryProductByEan
     *
     * Fetch product by EAN.
     *
     */
    public function testQueryProductByEan()
    {
    }

    /**
     * Test case for queryProductById
     *
     * Fetch product by ID.
     *
     */
    public function testQueryProductById()
    {
    }

    /**
     * Test case for queryProductTypes
     *
     * List of all product types.
     *
     */
    public function testQueryProductTypes()
    {
    }

    /**
     * Test case for queryProducts
     *
     * Search products by filter.
     *
     */
    public function testQueryProducts()
    {
    }
}
